#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, Ambiq
"""Generate THIRD-PARTY-NOTICES.md from the submodules' license files.

Walks the submodule trees listed in SUBMODULES (relative to the repository
root) and collects every file that looks like a license, notice, or EULA,
recursing into vendored `extern`/`third_party` payloads (e.g. the AmbiqSuite
SDK release trees, CMSIS, and TensorFlow Lite Micro's third_party/ deps).

A file matches if its name (case-insensitive) starts with "license",
"copying", or "notice", contains "eula" (this also catches AmbiqSuite's
AM-BSD-EULA.txt, which does not follow the LICENSE/COPYING/NOTICE stem), or
if it lives directly under a directory named "licenses" (this catches
modules/ns-cmsis-nn/LICENSES/*.txt).

This script does not judge or rewrite license text -- it only concatenates
whatever it finds, verbatim, under a heading for its repository-relative
path. It never modifies files inside the submodules.

Usage:
    python3 tools/gen_notices.py            # (re)write THIRD-PARTY-NOTICES.md
    python3 tools/gen_notices.py --check    # verify the file is up to date;
                                             # exits 1 and prints a diff-free
                                             # summary of drift if not.

Output is deterministic: submodule order is fixed, files within a submodule
are sorted by relative path, and all paths are repository-relative with
forward slashes (no absolute paths), so the generated file is reproducible
across machines and operating systems.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path, PurePosixPath

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "THIRD-PARTY-NOTICES.md"

# Submodule paths to walk, relative to REPO_ROOT. Kept explicit (rather than
# parsed from .gitmodules) so the set of trees this script touches is
# obvious on review. Update this list if a submodule is added or removed.
SUBMODULES = [
    "neuralspot",
    "modules/ns-cmsis-dsp",
    "modules/ns-cmsis-nn",
]

_NAME_PREFIXES = ("license", "copying", "notice")
# Restrict to plain-text-ish extensions so config/workflow files that merely
# start with "license" (e.g. .github/workflows/license-headers.yml) are not
# mistaken for license text.
_ALLOWED_SUFFIXES = ("", ".txt", ".md")


def _is_license_file(path: Path) -> bool:
    if path.suffix.lower() not in _ALLOWED_SUFFIXES:
        return False
    name_lower = path.name.lower()
    if any(name_lower.startswith(prefix) for prefix in _NAME_PREFIXES):
        return True
    if "eula" in name_lower:
        return True
    if path.parent.name.lower() in ("license", "licenses"):
        return True
    return False


def _find_license_files(submodule_root: Path) -> list[Path]:
    import os

    found: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(submodule_root):
        # Never descend into a submodule's own .git directory.
        dirnames[:] = [d for d in dirnames if d != ".git"]
        for filename in filenames:
            candidate = Path(dirpath) / filename
            if _is_license_file(candidate):
                found.append(candidate)
    found.sort(key=lambda p: p.relative_to(REPO_ROOT).as_posix())
    return found


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def _relposix(path: Path) -> str:
    return PurePosixPath(path.relative_to(REPO_ROOT).as_posix()).as_posix()


def generate() -> str:
    lines: list[str] = []
    lines.append("# Third-Party Notices")
    lines.append("")
    lines.append(
        "Generated by `tools/gen_notices.py`. Do not hand-edit; regenerate "
        "with `python3 tools/gen_notices.py`, and verify with "
        "`python3 tools/gen_notices.py --check`."
    )
    lines.append("")
    lines.append(
        "This file concatenates, verbatim, every LICENSE, COPYING, NOTICE, "
        "and EULA file found while walking the vendored submodule trees "
        "(`neuralspot`, `modules/ns-cmsis-dsp`, `modules/ns-cmsis-nn`), "
        "including their nested `extern`/`third_party` payloads (AmbiqSuite "
        "SDK releases, CMSIS, TensorFlow Lite Micro and its dependencies, "
        "and similar vendored trees). See `NOTICE` for a short, hand-written "
        "summary naming each submodule and its primary license."
    )
    lines.append("")

    for submodule in SUBMODULES:
        submodule_root = REPO_ROOT / submodule
        lines.append(f"## {submodule}")
        lines.append("")
        if not submodule_root.is_dir():
            lines.append(
                "_Submodule not checked out; run `git submodule update --init` "
                "and regenerate this file._"
            )
            lines.append("")
            continue

        license_files = _find_license_files(submodule_root)
        if not license_files:
            lines.append("_No LICENSE/COPYING/NOTICE/EULA files found._")
            lines.append("")
            continue

        for path in license_files:
            rel = _relposix(path)
            lines.append(f"### {rel}")
            lines.append("")
            lines.append("```")
            lines.append(_read_text(path).rstrip("\n"))
            lines.append("```")
            lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify THIRD-PARTY-NOTICES.md is up to date without writing it",
    )
    args = parser.parse_args(argv)

    content = generate()

    if args.check:
        existing = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if existing == content:
            print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is up to date.")
            return 0
        print(
            f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is out of date. "
            "Run `python3 tools/gen_notices.py` to regenerate.",
            file=sys.stderr,
        )
        return 1

    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
